### ISSUE TITLE
I wish I knew how to quit you (joke)

### ISSUE THREAD

**Issue by booyaa** [brrzap/tootstream#10]
hey, could you create a `quit` command? `CTRL-C` doesn't see to do anything, but this could caused by me running tootstream in `tmux` which in turn is in a `screen` session.

At the moment I've having to use `CTRL-Z` to suspend and kill the process.

**Comment by brrzap** [comment]
ha!  sorry, this is poorly documented.  `Ctrl-D` (on an empty prompt line), `:quit`, `:exit`, or `:q` will exit the program (these are builtin commands in click-repl; the prior click-shell provided a builtin quit/exit command).  i'll add a note to the help output.

Ctrl-C will of course cancel an in-progress command and return you safely to a fresh prompt.
