### ISSUE TITLE
Can't build after last commit

### ISSUE THREAD

**Issue by booyaa** [brrzap/tootstream#8]
## Error

```
$ python3 setup.py install

error in tootstream setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Invalid requirement, parse error at "'=1.0.14'"
```

## Setup

```
$ pip -V ; python -V ; git log --format="%H" -n 1

pip 9.0.1 from /home/pi/tootstream/tootstream/lib/python3.4/site-packages (python 3.4)
Python 3.4.2
27c43b0da92616043d5c4785d7801d502adca93a
```

**Comment by brrzap** [comment]
should be fixed in https://github.com/brrzap/tootstream/commit/d85426c4b1ac8e1c0590c0f55fc65fe34291f07d.

that fix also pulls in some debug logging that should be more configurable than it is; presently it just dumps the output in a file in current working directory.  sorry about the mess.
